Выполняет базовую стилизацию всех страниц
htmlacademy-adaptive/1796901-cat-energy-23 pull request #4
Opened 2021-08-10 19:33 UTC by Holder19

2021-08-11 07:39 UTC, firefoxic requested changes

2021-08-11 07:39 UTC, firefoxic commented on source/sass/global/fonts.scss
> +  font-family: "Oswald", sans-serif;
`@font-face` — это декларация шрифта, тут не должно быть фолбэков на веб-безопасный шрифт или родовое имя.
Фолбэки нужно прописывать там, где применяешь этот шрифт.

2021-08-11 07:39 UTC, firefoxic commented on source/sass/global/fonts.scss
> +  src: url("/source/fonts/oswaldmedium.woff2") format("woff2"),
Не ошибка, но для лучшей читабельности желательно при множественном значении переносить все его части на свои строки с увеличенным отступом (как у следующей строки).

2021-08-11 07:39 UTC, firefoxic commented on source/sass/global/fonts.scss
> +    url("/source/fonts/oswaldmedium.woff") format("woff");
Путь надо указывать не относительно корня проекта, а относительно файлатекущего. На сервере никакой папки source не будет.

2021-08-11 07:39 UTC, firefoxic commented on source/sass/blocks/nav-list.scss
> +  margin: 0;
У блока не должно быть позиционирования и марджинов.

2021-08-12 16:39 UTC, Holder19 commented on source/sass/blocks/nav-list.scss
> +  margin: 0;
если я добавлю это списку доп класс ,например, <ul class="nav-list nav-list-menu'>

2021-08-12 16:40 UTC, Holder19 commented on source/sass/blocks/nav-list.scss
> +  margin: 0;
это будет правильным решением,я ведь правильно понимаю?)

2021-08-12 16:58 UTC, Holder19 commented on source/sass/global/fonts.scss
> +    url("/source/fonts/oswaldmedium.woff") format("woff");
тогда вместо такой записи,нужно сделать вот такую?src: url("../../fonts/oswaldmedium.woff2");

2021-08-12 17:03 UTC, Holder19 commented on source/sass/global/fonts.scss
> +  src: url("/source/fonts/oswaldmedium.woff2") format("woff2"),
src:
    url("/source/fonts/oswaldmedium.woff2") format("woff2"),
    url("/source/fonts/oswaldmedium.woff") format("woff"); так?

2021-08-12 17:04 UTC, firefoxic commented on source/sass/global/fonts.scss
> +    url("/source/fonts/oswaldmedium.woff") format("woff");
Да 🙂

2021-08-12 17:06 UTC, firefoxic commented on source/sass/global/fonts.scss
> +  src: url("/source/fonts/oswaldmedium.woff2") format("woff2"),
ага, только с отступом желательно:
```css
src:
  url("/source/fonts/oswaldmedium.woff2") format("woff2"),
  url("/source/fonts/oswaldmedium.woff") format("woff"); 
```

2021-08-13 17:07 UTC, merged